name: Label PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    env:
      gh-token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@main
      - uses: Balastrong/github-typescript-action-test@main
        with:
          label: needs-review
