name: Label PR

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:    

jobs:
  label:
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@main
      - uses: Balastrong/ga-label-issue@main
        with:
          label: "needs-review"
          gh-token: ${{ secrets.GITHUB_TOKEN }}
